name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please check the backlog first to see if it's already planned.

  - type: dropdown
    id: type
    attributes:
      label: Feature Type
      options:
        - New command
        - New template
        - Workflow improvement
        - Configuration option
        - CLI enhancement
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: Add a command that...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions you've considered?

  - type: dropdown
    id: priority
    attributes:
      label: Suggested Priority
      description: How important is this to you?
      options:
        - P0 - Critical (blocking my work)
        - P1 - High (would significantly improve workflow)
        - P2 - Medium (nice to have)
        - P3 - Low (minor improvement)
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context, mockups, or examples
